import {HEROES,CARDS,createRun,enterBattle,playCard,endTurn,advance,intent,restore,serialise,availableNodes,chooseNode,selectTarget,RELICS,resolveRoom,buy,sell,usePotion} from './engine.js?v=3';

const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const keys={run:'veyrak.ascension.run.v3',archive:'veyrak.ascension.archive.v1',settings:'veyrak.ascension.settings.v1'};
let storageError=false;
function read(k){try{return localStorage.getItem(k);}catch{storageError=true;return null;}}
function write(k,v){try{localStorage.setItem(k,v);return true;}catch{storageError=true;notify('Your browser could not save. Keep this tab open to retain this run.');return false;}}
let run=restore(read(keys.run)),selected='kaerun',screen='title',settings={sound:false,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches},history=[],audio;
try{const s=JSON.parse(read(keys.settings));if(s&&typeof s.sound==='boolean'&&typeof s.motion==='boolean')settings=s;}catch{}
try{const a=JSON.parse(read(keys.archive));if(Array.isArray(a))history=a.filter(x=>x&&typeof x.seed==='string'&&HEROES.some(h=>h.id===x.hero)&&['won','lost','abandoned'].includes(x.outcome)&&Number.isInteger(x.turns)).slice(0,30);}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(kind){const paths={strike:'M7 25 23 9m-1-5 6 6M4 28l6-2-4-4-2 6Z',guard:'M16 3 27 8v9c0 6-11 12-11 12S5 23 5 17V8Z',surge:'m18 2-12 17h9l-1 11 12-18h-9Z',lock:'M9 14V9a7 7 0 0 1 14 0v5M6 14h20v16H6Zm10 6v5',core:'m16 2 12 14-12 14L4 16Z',back:'m20 6-10 10 10 10',pause:'M11 7v18m10-18v18',sound:'M5 13h6l8-7v20l-8-7H5Zm19-3q7 6 0 12'};return `<svg viewBox="0 0 32 32" aria-hidden="true"><path d="${paths[kind]||paths.core}"/></svg>`;}
function button(label,action,cls='gold',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function notify(text){$('#notice').textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').textContent='',6500);}
function sound(low=false){if(!settings.sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(low?165:440,audio.currentTime);o.frequency.exponentialRampToValueAtTime(low?65:660,audio.currentTime+.13);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.17);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.18);}catch{}}
function hero(){return HEROES.find(h=>h.id===(run?.hero||selected));}
function save(){if(run)write(keys.run,serialise(run));}
function record(outcome){if(!run||run.recorded)return;history.unshift({seed:run.seed,hero:run.hero,outcome,turns:run.turns,cards:run.cardsPlayed});history=history.slice(0,30);write(keys.archive,JSON.stringify(history));run.recorded=true;save();}
function persistAction(fn,...args){if(!fn(run,...args))return false;if(run.phase==='won'||run.phase==='lost')record(run.phase);save();return true;}
function title(){return `<main class="title screen"><div class="title-shade"></div><div class="title-content"><div class="crest">${icon('core')}</div><h1>Veyrak<span>Ascension</span></h1><div class="title-rule"></div><nav aria-label="Main menu">${run&&!['won','lost'].includes(run.phase)?button('Continue ascent','continue'):''}${button('Begin ascent','select')}${button('Archive','archive')}${button('Settings','settings')}</nav></div><footer><span>VEYATHUUN AWAITS</span><span>FIRST ASCENT · v0.3</span></footer></main>`;}
function select(){const h=HEROES.find(x=>x.id===selected);return `<main class="selection screen"><header class="topbar">${button(icon('back')+'<span>Back</span>','title','quiet')}<h1>Choose your Veyrakian</h1><span class="eyebrow council-label">Veyathuun Council</span></header><div class="select-stage"><div class="hero-display"><img class="hero-art" src="assets/${h.id}.png" alt="${h.name}" fetchpriority="high"></div><section class="dossier"><div class="dossier-mark">${icon('core')}</div><p class="eyebrow">Council dossier</p><h2>${h.name}</h2><p class="subtitle">${h.title}</p><div class="gold-rule"></div><div class="traits"><div>${icon(h.id==='kaerun'?'strike':'surge')}<span>${h.weapon}</span></div><div>${icon('guard')}<span>80 Vitality</span></div></div><label class="seed-label" for="seed">Run seed <span>Optional</span></label><input id="seed" maxlength="32" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="Leave blank for a new ascent"><p class="seed-help">Same seed. Same encounters.</p>${button('Begin ascent','start')}<p class="starter-note">10 starter cards · 7 stages · Branching routes</p></section></div><nav class="hero-roster" aria-label="Choose hero">${HEROES.map(h=>`<button class="hero-choice ${selected===h.id?'selected':''} ${!h.available?'locked':''}" data-action="hero" data-hero="${h.id}" ${h.available?`aria-pressed="${selected===h.id}"`:'aria-disabled="true"'} aria-label="${h.name}${h.available?'':', locked'}"><span class="portrait" style="--portrait-x:${h.portrait}%"></span><span class="hero-name">${h.name}${!h.available?'<small>Locked</small>':''}</span></button>`).join('')}</nav></main>`;}
function runHeader(label){return `<header class="topbar run-top"><div class="run-brand">Veyrak <span>Ascension</span></div><div class="run-location">${label}<small>SEED ${escape(run.seed)}</small></div>${button(icon('pause')+'<span>Menu</span>','pause','quiet')}</header>`;}
const nodeNames={battle:'Battle',boss:'Boss',shop:'Shop',chest:'Treasure',mystery:'Mystery',rest:'Sanctuary'};
const nodeIcons={battle:'⚔',boss:'♛',shop:'¤',chest:'▣',mystery:'?',rest:'✦'};
function inventoryBar(){return `<div class="inventory-bar"><span>♥ ${run.hp}/${run.maxHp}</span><span>¤ ${run.gold} gold</span>${button(`Deck · ${run.deck.length}`,'cards','quiet')}${button(`Potion · ${run.potions}`,'potion','quiet',run.potions&&run.hp<run.maxHp?'':'disabled')}<span>${run.relics.map(id=>`<span title="${RELICS[id].text}">${RELICS[id].name}</span>`).join(' · ')}</span>${run.blessing?`<span>+${run.blessing} Strength</span>`:''}${run.curse?`<span>Core drain: ${run.curse} turns</span>`:''}</div>`;}
function map(){const available=availableNodes(run);const pos=n=>({x:60+n.row*125,y:n.row===0||n.row===6?130:45+n.col*85});return `<main class="route screen">${runHeader('Choose your path')}<section class="branch-panel"><div class="map-heading"><h1>The gates of Veyathuun</h1><p>Follow the gold paths. Every choice shapes your deck.</p></div>${inventoryBar()}<div class="branch-scroll"><div class="branch-map"><svg viewBox="0 0 870 270" preserveAspectRatio="none" aria-hidden="true">${run.route.flatMap(n=>n.next.map(id=>{const v=run.route.find(x=>x.id===id),a=pos(n),b=pos(v);return `<path class="${run.visited.includes(n.id)&&run.visited.includes(id)?'travelled':run.current===n.id?'open-path':''}" d="M${a.x} ${a.y} L${b.x} ${b.y}"/>`;})).join('')}</svg>${run.route.map(n=>{const p=pos(n);return `<button class="branch-node ${available.includes(n.id)?'available':''} ${run.visited.includes(n.id)?'visited':''}" style="left:${p.x/8.7}%;top:${p.y/2.7}%" data-action="node" data-id="${n.id}" ${available.includes(n.id)?'':'disabled'} aria-label="Stage ${n.row+1}: ${nodeNames[n.type]}"><b>${run.visited.includes(n.id)?'✓':nodeIcons[n.type]}</b><span>${nodeNames[n.type]}</span></button>`;}).join('')}</div></div><p class="map-legend">⚔ Battle & card reward · ▣ Relic & supplies · ? Risk & reward · ¤ Buy / sell · ✦ Heal</p></section></main>`;}
function cardArt(id,cls=''){const t=CARDS[id].tile;return `<span class="sheet-card ${cls}" style="--cx:${t%5};--cy:${Math.floor(t/5)}" role="img" aria-label="${CARDS[id].name}"></span>`;}
function cardOffer(id,action,extra=''){const c=CARDS[id];return `<button class="offer-card" data-action="${action}" data-id="${id}" ${extra}>${cardArt(id)}<strong>${c.name}</strong><span>${c.cost} Core · ${c.text}</span></button>`;}
function room(){const kind=run.phase;let content='';if(kind==='chest')content=`<h1>The forgotten vault</h1><p>${run.room.relic?`${RELICS[run.room.relic].name} — ${RELICS[run.room.relic].text}`:'A cache of supplies.'}</p><p>${run.room.gold} gold + a healing potion.</p>${button('Claim treasure','room','gold','data-choice="claim"')}`;
if(kind==='rest')content=`<h1>Sanctuary</h1><p>Rest here to recover 24 Vitality.</p>${button('Rest & continue','room','gold','data-choice="rest"')}`;
if(kind==='mystery'){const k=run.room.kind;content=k==='cache'?`<h1>A warrior’s legacy</h1><p>Choose one abandoned technique for your deck.</p><div class="offers">${run.room.cards.map(id=>cardOffer(id,'room',`data-choice="${id}"`)).join('')}</div>`:k==='shrine'?`<h1>The amber shrine</h1><p>Offer 8 Vitality. Gain +1 Strength every turn for this run.</p>${button('Make the offering','room','gold',`data-choice="accept" ${run.hp<=8?'disabled':''}`)}`:`<h1>A whisper in the rift</h1><p>Gain ${CARDS[run.room.cards[0]].name} and 45 gold, but start your next two turns with only 2 Core.</p>${button('Accept the bargain','room','gold','data-choice="accept"')}`;content+=button('Leave untouched','room','quiet','data-choice="leave"');}
if(kind==='shop')content=`<h1>The wandering merchant</h1><p>Buy techniques and supplies. Sell spare cards for 10 gold (keep at least 5).</p><div class="shop-stock">${run.room.stock.map((x,i)=>`<article>${x.kind==='card'?cardArt(x.id):'<div class="item-symbol">'+(x.kind==='potion'?'✚':'◆')+'</div>'}<strong>${x.kind==='card'?CARDS[x.id].name:x.kind==='potion'?'Healing potion':RELICS[x.id].name}</strong><p>${x.kind==='card'?CARDS[x.id].text:x.kind==='potion'?'Restore 20 Vitality.':RELICS[x.id].text}</p>${button(x.sold?'Sold':`Buy · ${x.price} gold`,'buy','quiet',`data-index="${i}" ${x.sold||run.gold<x.price?'disabled':''}`)}</article>`).join('')}</div><div class="sell-list">${run.deck.map((id,i)=>button(`Sell ${CARDS[id].name} · 10`,'sell','quiet',`data-index="${i}" data-kind="card" ${run.deck.length<=5?'disabled':''}`)).join('')}${button('Sell potion · 12','sell','quiet',`data-kind="potion" ${run.potions?'':'disabled'}`)}</div>${button('Continue journey','room','gold','data-choice="leave"')}`;
return `<main class="route screen room-screen">${runHeader(nodeNames[kind])}<section class="room-panel">${inventoryBar()}${content}</section></main>`;}
function enemyArt(e){return `<svg class="enemy-art ${e.boss?'boss':''}" viewBox="0 0 280 340" role="img" aria-label="${e.name}, a floating crystalline guardian" style="--enemy:${e.colour}"><defs><linearGradient id="crystal" x2="1" y2="1"><stop stop-color="${e.colour}"/><stop offset=".48" stop-color="#283440"/><stop offset="1" stop-color="#0a111d"/></linearGradient></defs><ellipse cx="140" cy="311" rx="65" ry="12" fill="#000" opacity=".3"/><g class="crystal-body"><circle cx="140" cy="165" r="100" fill="none" stroke="${e.colour}" opacity=".2"/><path d="m140 28 73 84-21 103-52 71-52-71-21-103Z" fill="url(#crystal)" stroke="${e.colour}" stroke-width="2"/><path d="m140 28-22 103 22 155 24-155Zm-73 84 73 53 73-53M88 215l52-50 52 50" fill="none" stroke="${e.colour}" opacity=".8"/><path d="m140 114 27 48-27 41-27-41Z" fill="${e.colour}"/><path d="m43 93 20 37-14 64-24-34Zm194 0-20 37 14 64 24-34Z" fill="url(#crystal)" stroke="${e.colour}"/><path d="m94 64 46-48 46 48M85 269l55 34 55-34" fill="none" stroke="#ddbd7b" stroke-width="3"/><circle cx="140" cy="161" r="10" fill="#fff5d7"/></g></svg>`;}
function health(value,max,label){return `<div class="health"><div class="health-label"><span>${label}</span><strong>${value} <small>/ ${max}</small></strong></div><div class="health-track" role="meter" aria-label="${label} health" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${value/max*100}%"></span></div></div>`;}
function combat(){const b=run.battle;return `<main class="battle screen">${runHeader(`Stage ${run.index+1} / 7 · ¤ ${run.gold}`)}<section class="arena"><div class="fighter player"><div class="fighter-info">${health(run.hp,run.maxHp,hero().name)}<span class="block">${icon('guard')} ${run.block} Block ${b.strength?`· +${b.strength} Strength`:''}</span></div><img class="combat-hero" src="assets/${run.hero}.png" alt="${hero().name}"></div><div class="turn-medallion"><span>TURN</span><strong>${b.turn}</strong></div><div class="enemy-group">${b.enemies.map((e,i)=>{if(!e.hp)return '';const m=intent(run,i);return `<button class="enemy-target ${i===b.target?'targeted':''}" data-action="target" data-index="${i}" aria-label="Target ${e.name}" aria-pressed="${i===b.target}"><div class="fighter-info">${health(e.hp,e.maxHp,e.name)}<span class="intent">${m.kind==='stun'?'Stunned — skips action':m.kind==='attack'?`Attacks for ${m.value}`:m.kind==='guard'?`Gains ${m.value} Block`:'Gathering power'}</span><small>${e.mark?`${e.mark} Mark · `:''}${e.block?`${e.block} Block · `:''}${i===b.target?'Targeted':''}</small></div>${enemyArt(e)}</button>`;}).join('')}</div></section><section class="combat-controls"><div class="combat-toolbar"><div class="core-count">${icon('core')}<strong>${run.core}<small> / 3</small></strong><span>CORE</span></div><p class="combat-message" aria-live="polite">Tap a card to inspect · Tap an enemy to target</p>${button('End turn','end','gold end-turn')}</div><div class="hand" aria-label="Your hand">${b.hand.map((id,i)=>`<button class="ability-card ${CARDS[id].cost>run.core?'unaffordable':''}" style="--fan:${i-(b.hand.length-1)/2}" data-action="inspect" data-index="${i}" aria-label="Inspect ${CARDS[id].name}">${cardArt(id)}</button>`).join('')}${b.hand.length?'':'<p class="empty-hand">End your turn to draw again.</p>'}</div><div class="pile-row">${button(`Draw · ${b.draw.length}`,'draw','text-button')}${button(`Potion · ${run.potions}`,'potion','text-button')}${button(`Discard · ${b.discard.length}`,'discard','text-button')}</div></section></main>`;}
function outcome(){const won=run.phase==='won',lost=run.phase==='lost';return `<main class="result screen">${runHeader('The first ascent')}<section class="result-panel"><div class="result-symbol">${icon(lost?'guard':'core')}</div><p class="eyebrow">${lost?'The ascent ends':won?'The summit is yours':'Path cleared'}</p><h1>${lost?'Rise again.':won?'Ascension':'Victory'}</h1><p>${lost?'Veyathuun will remember your resolve.':won?'You have defeated the Gate Warden.':`The encounter is complete. Choose a card to add to your deck.`}</p><div class="result-stats"><div><strong>${run.hp}</strong><span>Vitality remaining</span></div><div><strong>${run.turns}</strong><span>Turns played</span></div></div>${lost||won?button('Return to title','title'):`<p>+30 gold · Choose one card, or skip.</p><div class="offers">${run.rewards.map(id=>cardOffer(id,'reward')).join('')}</div>${button('Skip reward','advance','quiet')}`}<p class="small muted">Seed ${escape(run.seed)}</p></section></main>`;}
function render(){document.body.classList.toggle('reduced-motion',!settings.motion);const views={title,select,map,combat,victory:outcome,won:outcome,lost:outcome,shop:room,chest:room,mystery:room,rest:room};app.innerHTML=views[screen]();document.title=`Veyrak: Ascension${screen==='combat'?' · Battle':''}`;}
function navigate(next){screen=next;render();window.scrollTo(0,0);}
function openModal(title,content){modal.innerHTML=`<div class="modal-heading"><h2>${title}</h2>${button('×','close','close','aria-label="Close dialog"')}</div>${content}`;modal.showModal();}
function confirmNew(){const seed=$('#seed')?.value.trim()||crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase();const start=()=>{if(run&&!['won','lost'].includes(run.phase))record('abandoned');run=createRun(seed,selected);save();navigate('map');};if(run&&!['won','lost'].includes(run.phase)){openModal('Replace current ascent?',`<p>Your saved run will end. Begin a new ascent with ${HEROES.find(h=>h.id===selected).name}?</p><div class="dialog-actions">${button('Keep current run','close','quiet')}${button('Begin new ascent','confirm-start')}</div>`);pendingStart=start;}else start();}
let pendingStart;
function settingsDialog(){openModal('Settings',`<div class="setting"><div><strong>Sound effects</strong><p>Soft menu and combat sounds.</p></div><button class="toggle" role="switch" aria-checked="${settings.sound}" data-action="sound">${settings.sound?'On':'Off'}</button></div><div class="setting"><div><strong>Animation</strong><p>Movement and combat effects.</p></div><button class="toggle" role="switch" aria-checked="${settings.motion}" data-action="motion">${settings.motion?'On':'Off'}</button></div><p class="small muted">Saves are stored on this device and browser.</p>`);}
function help(){openModal('Your first battle',`<ol class="help"><li>Each turn starts with <b>3 Core</b> and <b>5 cards</b>.</li><li>Tap a card to inspect it, then choose Play card. Its top number is its Core cost.</li><li><b>Strike</b> and <b>Gauntlet Smash</b> damage the enemy. <b>Guard</b> absorbs damage this turn.</li><li>Read the enemy intention above it, then choose <b>End turn</b>.</li><li>Unused cards are discarded. The discard pile reshuffles when the draw pile empties.</li><li>Block expires at your next turn. Vitality carries throughout the ascent.</li></ol>${button('Ready','close')}`);}
function animate(target,cls){if(!settings.motion)return;const el=$(target);el?.classList.add(cls);}
app.addEventListener('click',handle);modal.addEventListener('click',handle);
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
function handle(event){const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;sound();
 switch(a){
 case 'title':modal.close();navigate('title');break;
 case 'select':navigate('select');break;
 case 'hero':if(!HEROES.find(h=>h.id===el.dataset.hero).available){notify('This hero is locked. Progression unlocks arrive in a later stage.');break;} {const seed=$('#seed').value;selected=el.dataset.hero;render();$('#seed').value=seed;break;}
 case 'start':confirmNew();break;
 case 'confirm-start':modal.close();pendingStart?.();pendingStart=null;break;
 case 'continue':navigate(run.phase);break;
 case 'node':if(persistAction(chooseNode,el.dataset.id))navigate(run.phase);break;
 case 'target':if(persistAction(selectTarget,Number(el.dataset.index)))render();break;
 case 'inspect':{const i=Number(el.dataset.index),id=run.battle.hand[i],c=CARDS[id];openModal(c.name,`<div class="inspect-card">${cardArt(id)}<div><p class="eyebrow">${c.type} · ${c.cost} Core</p><p>${c.text}</p>${c.mark?'<p class="small">Mark lasts across turns, losing 1 after each enemy action. Mark enables Gauntlet Smash’s bonus.</p>':''}<p class="small">Target: ${run.battle.enemies[run.battle.target].name}</p>${button(c.cost>run.core?'Not enough Core':'Play card','play','gold',`data-index="${i}" ${c.cost>run.core?'disabled':''}`)}${button('Back to hand','close','quiet')}</div></div>`);break;}
 case 'reward':if(persistAction(advance,el.dataset.id))navigate(run.phase);break;
 case 'room':if(persistAction(resolveRoom,el.dataset.choice))navigate(run.phase);break;
 case 'buy':if(persistAction(buy,Number(el.dataset.index)))render();break;
 case 'sell':if(persistAction(sell,el.dataset.kind,Number(el.dataset.index)))render();break;
 case 'potion':if(persistAction(usePotion)){render();notify('Recovered 20 Vitality, up to your maximum.');}break;
 case 'enter':if(persistAction(enterBattle)){navigate('combat');if(run.turns===1&&!history.length)help();}break;
 case 'play':{modal.close();const card=CARDS[run.battle?.hand[Number(el.dataset.index)]];if(persistAction(playCard,Number(el.dataset.index))){navigate(run.phase);animate(card?.block||card?.type==='skill'?'.player':'.enemy',card?.block||card?.type==='skill'?'guard-flash':'hit');if(card?.damage)animate('.combat-hero','attack-animation');}break;}
 case 'end':if(persistAction(endTurn)){navigate(run.phase);animate('.player','hit');sound(true);}break;
 case 'advance':if(persistAction(advance))navigate('map');break;
 case 'close':modal.close();break;
 case 'settings':settingsDialog();break;
 case 'sound':case 'motion':settings[a]=!settings[a];write(keys.settings,JSON.stringify(settings));modal.close();render();settingsDialog();break;
 case 'help':help();break;
 case 'pause':openModal('Ascent paused',`<p>${storageError?'Saving is unavailable. Keep this tab open.':'Your progress has been saved.'}</p><div class="pause-actions">${button('Resume','close')}${button('View cards','cards','quiet')}${button('How to play','help','quiet')}${button('Return to title','title','quiet')}</div>`);break;
 case 'cards':{const counts=[...new Set(run.deck)].map(id=>({id,n:run.deck.filter(x=>x===id).length}));openModal('Your deck',`<p>${run.deck.length} cards · New cards are earned during this ascent.</p><div class="collection-grid">${counts.map(x=>`<article class="collection-card">${cardArt(x.id)}<div><strong>${CARDS[x.id].name} ×${x.n}</strong><span>${CARDS[x.id].cost} Core · ${CARDS[x.id].text}</span></div></article>`).join('')}</div>`);break;
 }
 case 'archive':openModal('Ascent archive',history.length?`<p class="muted">Your last ${history.length} ascents on this device.</p><div class="archive-list">${history.map(r=>`<article><div><strong>${HEROES.find(h=>h.id===r.hero).name}</strong><span>${r.outcome==='won'?'Summit reached':r.outcome==='lost'?'Fallen':'Abandoned'} · ${r.turns} turns</span></div><code>${escape(r.seed)}</code></article>`).join('')}</div>`:'<div class="empty-archive">'+icon('core')+'<p>Your story begins with your first ascent.</p><p class="small muted">Completed runs and their seeds will appear here.</p></div>');break;
 case 'draw':case 'discard':{const pile=run.battle[a];const counts=Object.keys(CARDS).map(id=>({id,n:pile.filter(c=>c===id).length})).filter(x=>x.n);openModal(a==='draw'?'Draw pile':'Discard pile',`<p class="muted">${a==='draw'?'Card counts only — draw order stays hidden.':'Cards return to the draw pile when it empties.'}</p><ul class="pile-list">${counts.map(x=>`<li>${CARDS[x.id].name}<strong>× ${x.n}</strong></li>`).join('')||'<li>Empty</li>'}</ul>`);break;}
 }
}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.open&&['combat','map'].includes(screen)){e.preventDefault();openModal('Ascent paused',`<div class="pause-actions">${button('Resume','close')}${button('Return to title','title','quiet')}</div>`);}});
window.addEventListener('pagehide',save);
render();if(storageError)notify('Saving is unavailable in this browser. Your current run will work in this tab.');
for(const src of ['council-background','kaerun','ilyra','approved-selection']){const i=new Image();i.src=`assets/${src}.png`;}

