import {DEFAULT_STARTERS,FLEX_SLOTS,LEVEL_UNLOCKS,STARTER_CHALLENGES,starterCatalog,unlockedStarterCards,validateLoadout} from './starter-decks.js?v=2';

export function renderDeckBuilder({hero,collection,level,cards,cardArt,button,escape,draft,slot,dirty,availableHeroes=['kaerun','ilyra']}){
 const h=collection.heroes[hero],unlocked=unlockedStarterCards(hero,collection,level),title=hero.charAt(0).toUpperCase()+hero.slice(1);
 const deck=[...DEFAULT_STARTERS[hero]];FLEX_SLOTS[hero].forEach((index,i)=>deck[index]=draft[i]);
 const flexible=FLEX_SLOTS[hero],cost=draft.reduce((n,id)=>n+cards[id].cost,0);
 const preview=id=>button(cardArt(id)+'<strong>'+escape(cards[id].name)+'</strong><small>'+cards[id].cost+' Core · '+escape(cards[id].text)+'</small>','starter-inspect','starter-preview','data-id="'+id+'"');
 const slots=deck.map((id,index)=>{const f=flexible.indexOf(index);return '<article class="starter-slot '+(f>=0?'flexible':'protected')+' '+(f===slot?'chosen':'')+'">'+(f>=0?button('Flexible '+(f+1),'deck-slot','quiet','data-slot="'+f+'" aria-pressed="'+(slot===f)+'"'):'<span class="protected-label">Fixed · Hero foundation</span>')+preview(id)+'</article>';}).join('');
 const milestones=Object.entries(LEVEL_UNLOCKS[hero]).map(([threshold,options])=>{
  const chosen=h.choices[threshold],ready=level>=Number(threshold);
  return '<article class="starter-milestone"><h3>Level '+threshold+' · Choose one technique</h3>'+(chosen?'<p>Unlocked: '+escape(cards[chosen].name)+'</p>':ready?'<p>You have earned this choice. It is permanent for this hero.</p><div class="starter-unlock-options">'+options.map(id=>'<section>'+preview(id)+button(unlocked.includes(id)?'Already unlocked':'Unlock '+escape(cards[id].name),'deck-unlock','gold','data-id="'+id+'" data-level="'+threshold+'" '+(unlocked.includes(id)?'disabled':''))+'</section>').join('')+'</div>':'<p>Reach hero level '+threshold+' to choose from '+options.map(id=>escape(cards[id].name)).join(', ')+'.</p>')+'</article>';
 }).join('');
 const challenges=STARTER_CHALLENGES[hero].map(c=>{const value=Math.min(c.goal,h.stats[c.stat]),done=value>=c.goal;return '<article class="starter-challenge"><strong>'+escape(c.name)+(done?' · Complete':'')+'</strong><p>'+escape(c.text)+'</p><progress max="'+c.goal+'" value="'+value+'" aria-label="'+escape(c.name)+'"></progress><small>'+value+' / '+c.goal+' · '+(done?'Unlocked: ':'Reward: ')+escape(cards[c.card].name)+'</small></article>';}).join('');
 const catalog=starterCatalog(hero).map(id=>{
  const owned=unlocked.includes(id),found=h.seen.includes(id)||owned;let requirement='Available in your original starter deck.';
  if(!DEFAULT_STARTERS[hero].includes(id)){
   const paths=[];for(const [threshold,options] of Object.entries(LEVEL_UNLOCKS[hero]))if(options.includes(id))paths.push('Choose at hero level '+threshold);
   for(const c of STARTER_CHALLENGES[hero])if(c.card===id)paths.push(c.text);requirement=paths.join(' or ');
  }
  const candidate=[...draft];candidate[slot]=id;const error=owned?validateLoadout(hero,candidate,collection,level,cards):'Locked';
  return '<article class="starter-collection-card '+(owned?'unlocked':'locked')+'">'+(found?preview(id):'<div class="undiscovered-card" aria-label="Undiscovered card">?</div><strong>'+escape(cards[id].name)+'</strong>')+'<p>'+escape(owned?'Unlocked for this hero':requirement)+'</p>'+(owned?button(draft[slot]===id?'Selected':'Use in flexible slot '+(slot+1),'deck-pick','quiet','data-id="'+id+'" '+(error||draft[slot]===id?'disabled':''))+(error?'<small>'+escape(error)+'</small>':''):'<small>'+(found?'Discovered during an ascent':'Discover during an ascent to reveal its artwork')+'</small>')+'</article>';
 }).join('');
 return '<main class="deck-builder screen"><header class="topbar">'+button('Back','deck-back','quiet')+'<h1>Starter Deck Builder</h1><span>'+title+' · Level '+level+'</span></header><section class="deck-builder-panel"><nav class="deck-hero-tabs" aria-label="Starter deck hero">'+availableHeroes.map(id=>button(id.charAt(0).toUpperCase()+id.slice(1),'deck-hero','quiet '+(id===hero?'active':''),'data-hero="'+id+'" aria-pressed="'+(id===hero)+'"')).join('')+'</nav><p class="deck-builder-intro">10 cards · 6 fixed cards · 4 flexible slots. Select a flexible slot, then choose an unlocked card below. Saves apply to new ascents.</p><div class="starter-deck-grid">'+slots+'</div><div class="deck-loadout-actions"><span role="status">'+(dirty?'Unsaved changes':'Saved starter deck')+' · Flexible cost '+cost+' / 6 Core</span>'+button('Save starter deck','deck-save','gold',!dirty?'disabled':'')+button('Restore default','deck-reset','quiet')+'</div><p class="small muted">At most two copies of each card in the flexible slots and two cards costing 2 Core. Upgraded cards and cards costing more than 2 Core remain run rewards.</p><h2>Starter collection</h2><div class="starter-collection-grid">'+catalog+'</div><h2>Level unlocks</h2>'+milestones+'<h2>Hero challenges</h2><p>Progress carries across ascents, including defeats. Challenges begin tracking with this update.</p><div class="starter-challenges">'+challenges+'</div></section></main>';
}
