import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';

// Execute the actual app handlers against a minimal DOM to verify the menu/save flow.
function appHarness(initial={}){
 const data=new Map(Object.entries(initial)),app={innerHTML:'',addEventListener(){}},notice={textContent:''},modal={innerHTML:'',open:false,addEventListener(){},showModal(){this.open=true;},close(){this.open=false;}},seed={value:'DECK-UI'};
 const context=vm.createContext({console,structuredClone,crypto:webcrypto,localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},matchMedia:()=>({matches:false}),setTimeout:()=>0,clearTimeout(){},requestAnimationFrame(){},Image:class{},window:{addEventListener(){},scrollTo(){}},document:{title:'',querySelector:s=>({'#app':app,'#modal':modal,'#notice':notice,'#seed':seed}[s]||null),addEventListener(){},body:{classList:{toggle(){}}}}});
 const files=['progression.js','beasts.js','combat-feedback.js','starter-decks.js','engine.js','deck-builder.js','app.js'];
 const source=files.map(file=>fs.readFileSync(new URL('../'+file,import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace(/^export \{.*;$/gm,'').replace(/\bexport (?=(?:const|function|async function|class))/g,'')).join('\n');
 vm.runInContext(source,context);
 return {data,app,modal,eval:code=>vm.runInContext(code,context),click:(action,extras={})=>{context.nextAction={action,...extras};vm.runInContext('handle({target:{closest:()=>({dataset:nextAction,disabled:false})}})',context);}};
}
test('main menu opens Deck Builder with ten labelled slots and four editable slots',()=>{const h=appHarness();assert.match(h.app.innerHTML,/Deck Builder/);h.click('deck-builder');assert.equal((h.app.innerHTML.match(/class="starter-slot /g)||[]).length,10);assert.equal((h.app.innerHTML.match(/data-action="deck-slot"/g)||[]).length,4);assert.match(h.app.innerHTML,/Fixed · Hero foundation/);});
test('unlock, swap, save, reload and new ascent use the saved deck',()=>{const h=appHarness({'veyrak.ascension.progression.v1':JSON.stringify({kaerunXp:120,ilyraXp:0})});h.click('deck-builder');h.click('deck-unlock',{level:'2',id:'scout'});h.click('deck-pick',{id:'scout'});assert.match(h.app.innerHTML,/Unsaved changes/);h.click('deck-save');assert.match(h.app.innerHTML,/Saved starter deck/);const saved=h.data.get('veyrak.ascension.starter.v1');assert.equal(JSON.parse(saved).heroes.kaerun.loadout[0],'scout');const reloaded=appHarness(Object.fromEntries(h.data));reloaded.click('select');reloaded.click('start');assert.equal(reloaded.eval('run.deck[2]'),'scout');assert.equal(reloaded.eval('run.deck.length'),10);});
test('unsaved edits prompt before switching heroes and defaults do not change active runs',()=>{const h=appHarness();h.click('deck-builder');h.click('deck-pick',{id:'targetbreaker'});assert.match(h.app.innerHTML,/Unsaved changes/);h.click('deck-hero',{hero:'ilyra'});assert.equal(h.modal.open,true);h.click('deck-discard',{kind:'deck-hero',destination:'ilyra'});assert.match(h.app.innerHTML,/Ilyra · Level 1/);assert.equal(h.eval('deckDraft[0]'),'arcbolt');h.click('deck-back');h.click('select');h.click('start');const before=h.eval('JSON.stringify(run.deck)');h.click('title');h.click('deck-builder');h.click('deck-reset');h.click('deck-save');assert.equal(h.eval('JSON.stringify(run.deck)'),before);});
test('failed permanent save leaves collection and draft state uncommitted',()=>{const h=appHarness();h.click('deck-builder');h.click('deck-pick',{id:'targetbreaker'});h.eval('localStorage.setItem=()=>{throw Error("quota")};');h.click('deck-save');assert.equal(h.eval('starterCollection.heroes.kaerun.loadout[0]'),'strike');assert.equal(h.eval('deckDirty()'),true);});
test('Vaelis remains locked below Account Rank 5 in selection and Deck Builder',()=>{const h=appHarness();h.click('select');h.click('hero',{hero:'vaelis'});assert.equal(h.eval('selected'),'kaerun');h.click('deck-builder',{hero:'vaelis'});assert.equal(h.eval('screen'),'select');assert.match(h.app.innerHTML,/Rank 5/);});
test('existing shared XP unlocks Vaelis, his deck and a reloadable ascent',()=>{const h=appHarness({'veyrak.ascension.progression.v1':JSON.stringify({kaerunXp:300,ilyraXp:390})});assert.match(h.app.innerHTML,/Account Rank 5/);h.click('select');h.click('hero',{hero:'vaelis'});assert.match(h.app.innerHTML,/Poisoned dual blades/);h.click('deck-builder');assert.match(h.app.innerHTML,/Vaelis · Level 1/);assert.equal((h.app.innerHTML.match(/data-action="deck-slot"/g)||[]).length,4);h.click('deck-pick',{id:'toxicprimer'});h.click('deck-save');h.click('deck-back');h.click('start');assert.equal(h.eval('run.hero'),'vaelis');assert.equal(h.eval('run.deck[2]'),'toxicprimer');const reload=appHarness(Object.fromEntries(h.data));assert.equal(reload.eval('run.hero'),'vaelis');reload.click('continue');assert.ok(reload.app.innerHTML.length>0);});
test('crossing Rank 5 unlocks Vaelis and repeated saves do not award XP twice',()=>{const h=appHarness({'veyrak.ascension.progression.v1':JSON.stringify({kaerunXp:680,ilyraXp:0})});h.click('select');h.click('start');h.eval('run.characterXpEarned=12;save();save();');assert.equal(h.eval('progression.kaerunXp'),692);h.click('title');assert.match(h.app.innerHTML,/Vaelis unlocked/);const reload=appHarness(Object.fromEntries(h.data));assert.equal(reload.eval('progression.kaerunXp'),692);});
test('account XP checkpoint prevents double credit when run saving fails after XP saving',()=>{const h=appHarness();h.click('select');h.click('start');h.eval('const realSet=localStorage.setItem;localStorage.setItem=(key,value)=>{if(key===keys.run)throw Error("quota");realSet(key,value);};run.characterXpEarned=12;save();');const reload=appHarness(Object.fromEntries(h.data));assert.equal(reload.eval('progression.kaerunXp'),12);reload.eval('run.characterXpEarned=12;save();');assert.equal(reload.eval('progression.kaerunXp'),12);});
test('failed XP saving can be retried without losing rank progress',()=>{const h=appHarness();h.click('select');h.click('start');h.eval('const realSet=localStorage.setItem;localStorage.setItem=()=>{throw Error("quota")};run.characterXpEarned=12;save();');assert.equal(h.eval('progression.kaerunXp'),0);assert.equal(h.eval('run.characterXpBanked'),0);h.eval('localStorage.setItem=realSet;save();');assert.equal(h.eval('progression.kaerunXp'),12);});
