import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,enterBattle,playCard,endTurn,advance,intent,serialise,restore,CARDS} from '../engine.js';

function choose(run){const b=run.battle;const affordable=b.hand.map((id,i)=>({...CARDS[id],i})).filter(c=>c.cost<=run.core);const hit=intent(run);const kill=affordable.find(c=>c.damage>=b.enemy.hp+b.enemy.block);if(kill)return kill.i;const guard=affordable.find(c=>c.block&&hit.kind==='attack'&&run.block<hit.value);if(guard)return guard.i;const damage=affordable.filter(c=>c.damage).sort((a,b)=>b.damage/b.cost-a.damage/a.cost)[0];return damage?.i??-1;}
function finish(seed){const r=createRun(seed);let safety=0;while(!['won','lost'].includes(r.phase)&&safety++<2000){if(r.phase==='map')enterBattle(r);else if(r.phase==='victory')advance(r);else{const i=choose(r);if(i>=0)playCard(r,i);else endTurn(r);}}assert.ok(safety<2000);return r;}

test('same seed produces identical route, draws and complete run; different seeds vary',()=>{assert.deepEqual(finish('SAME-SEED'),finish('SAME-SEED'));assert.notDeepEqual(createRun('A').encounters,createRun('B').encounters);});
test('reload preserves future shuffles and enemy intentions',()=>{const a=createRun('RELOAD');enterBattle(a);playCard(a,0);endTurn(a);const b=restore(serialise(a));assert.ok(b);for(let i=0;i<8;i++){endTurn(a);endTurn(b);assert.deepEqual(a,b);} });
test('Core cost, out-of-range actions, turn resets and card conservation',()=>{const r=createRun('COST');enterBattle(r);assert.equal(r.battle.hand.length,5);assert.equal(r.core,3);assert.equal(playCard(r,30),false);assert.equal(playCard(r,-1),false);while(r.core&&r.phase==='combat'){const i=r.battle.hand.findIndex(c=>CARDS[c].cost<=r.core);if(i<0)break;playCard(r,i);}const before=serialise(r);if(r.core===0){assert.equal(playCard(r,0),false);assert.equal(serialise(r),before);}endTurn(r);assert.equal(r.core,3);assert.equal(r.battle.hand.length,5);assert.equal(r.battle.draw.length+r.battle.hand.length+r.battle.discard.length,10);assert.equal(r.block,0);});
test('enemy attacks follow exactly the displayed intent, with block mitigation',()=>{const r=createRun('INTENT');enterBattle(r);const b=r.battle;b.enemy.move=b.enemy.moves.findIndex(m=>m.kind==='attack');r.block=4;const hp=r.hp,m=intent(r);endTurn(r);assert.equal(r.hp,hp-Math.max(0,m.value-4));});
test('victory advances once; defeat and win reject further combat',()=>{const r=createRun('WIN');enterBattle(r);r.battle.enemy.hp=1;r.battle.enemy.block=0;r.battle.hand=['strike'];playCard(r,0);assert.equal(r.phase,'victory');assert.equal(playCard(r,0),false);assert.equal(endTurn(r),false);assert.equal(advance(r),true);assert.equal(r.index,1);assert.equal(advance(r),false);assert.equal(r.hp,80);enterBattle(r);r.hp=1;r.battle.enemy.move=r.battle.enemy.moves.findIndex(m=>m.kind==='attack');endTurn(r);assert.equal(r.phase,'lost');assert.equal(enterBattle(r),false);assert.equal(endTurn(r),false);});
test('locked heroes and invalid/corrupt saves are rejected',()=>{assert.throws(()=>createRun('A','vaelis'));assert.equal(restore('{broken'),null);assert.equal(restore('null'),null);const r=createRun('SAVE');assert.ok(restore(serialise(r)));r.rng=-1;assert.equal(restore(serialise(r)),null);const b=createRun('SAVE');enterBattle(b);b.battle.hand[0]='script';assert.equal(restore(serialise(b)),null);const c=createRun('SAVE');c.encounters[0].hp=0;assert.equal(restore(serialise(c)),null);});
test('route and battle saves restore at every playable checkpoint',()=>{const r=createRun('CHECKPOINT');let n=0;while(!['won','lost'].includes(r.phase)&&n++<2000){assert.ok(restore(serialise(r)),`${r.phase} save`);if(r.phase==='map')enterBattle(r);else if(r.phase==='victory')advance(r);else{const i=choose(r);i>=0?playCard(r,i):endTurn(r);}}assert.ok(restore(serialise(r)));});
test('starter trial is winnable across a representative seed set',()=>{const results=Array.from({length:30},(_,i)=>finish('TRIAL-'+i));const wins=results.filter(r=>r.phase==='won').length;assert.ok(wins>=20,`${wins}/30 victories using a conservative strategy`);});
