import test from 'node:test';import assert from 'node:assert/strict';import * as E from '../engine.js';
const battle=()=>{const r=E.createRun('CHECK');E.enterBattle(r);return r;};
function hand(r,ids){r.battle.hand=ids;r.core=20;for(const e of r.battle.enemies){e.hp=100;e.maxHp=100;e.block=0;}}
test('seeded routes fork, reconnect and reject unreachable/repeated choices',()=>{const r=E.createRun('A');assert.deepEqual(r,E.createRun('A'));assert.notDeepEqual(r.route,E.createRun('B').route);assert.equal(E.chooseNode(r,'2-0'),false);E.chooseNode(r,'0-0');assert.equal(E.chooseNode(r,'0-0'),false);assert.equal(r.deck.length,10);assert.equal(new Set(r.deck).size,4);});
test('all ten printed card effects including Mark, stun and area damage',()=>{const r=battle();hand(r,['targetbreaker','gauntletsmash']);E.playCard(r,0);assert.equal(r.battle.enemies[0].mark,2);E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,82);hand(r,['stonebulwark','seismicpunch']);E.playCard(r,0);E.playCard(r,0);const hp=r.hp;E.endTurn(r);assert.equal(r.hp,hp);hand(r,['ironskin','strike','guard','deflect','focus','cleave']);r.block=0;E.playCard(r,0);assert.equal(r.block,8);assert.equal(r.battle.strength,1);E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,93);E.playCard(r,0);E.playCard(r,0);assert.equal(r.block,18);const core=r.core;E.playCard(r,0);assert.equal(r.core,core);r.battle.enemies.push(structuredClone(r.battle.enemies[0]));E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,84);assert.equal(r.battle.enemies[1].hp,84);});
test('reward selected once; shop transactions conserve gold and prevent repeat buying',()=>{const r=battle();r.battle.enemies[0].hp=1;hand(r,['strike']);r.battle.enemies[0].hp=1;E.playCard(r,0);assert.equal(r.phase,'victory');const id=r.rewards[0];assert.equal(E.advance(r,id),true);assert.equal(r.deck.length,11);assert.equal(E.advance(r,id),false);r.phase='shop';r.room={stock:[{kind:'card',id:'deflect',price:25,sold:false}]};const gold=r.gold;assert.equal(E.buy(r,0),true);assert.equal(r.gold,gold-25);assert.equal(E.buy(r,0),false);assert.equal(E.sell(r,'card',0),true);assert.equal(r.gold,gold-15);});
test('save/reload preserves exact state and future random draws',()=>{const a=battle();E.endTurn(a);const b=E.restore(E.serialise(a));assert.ok(b);E.endTurn(a);E.endTurn(b);assert.deepEqual(a,b);assert.equal(E.restore('{}'),null);a.deck[0]='bad';assert.equal(E.restore(E.serialise(a)),null);});
test('chests reveal once, potions work and mystery Core drain expires',()=>{const r=E.createRun('CHEST');r.phase='chest';r.room={bad:false,relic:'amber',gold:25,revealed:false};assert.ok(E.resolveRoom(r,'open'));assert.equal(r.potions,1);assert.equal(r.room.revealed,true);assert.equal(E.resolveRoom(r,'open'),false);assert.ok(E.resolveRoom(r,'leave'));r.hp=40;assert.ok(E.usePotion(r));assert.equal(r.hp,60);r.phase='mystery';r.room={kind:'rift',cards:['cleave']};E.resolveRoom(r,'accept');assert.equal(r.curse,2);E.enterBattle(r);assert.equal(r.core,2);E.endTurn(r);assert.equal(r.core,4);E.endTurn(r);assert.equal(r.core,7);});
test('reachable runs across seeds finish with valid checkpoints',()=>{for(let seed=0;seed<15;seed++){const r=E.createRun('RUN'+seed);for(let step=0;step<500&&!['won','lost'].includes(r.phase);step++){assert.ok(E.restore(E.serialise(r)),r.phase);if(r.phase==='map')E.chooseNode(r,E.availableNodes(r)[0]);else if(r.phase==='combat'){let i=r.battle.hand.findIndex(id=>E.CARDS[id].cost<=r.core&&(E.CARDS[id].damage||E.CARDS[id].block));if(i<0)E.endTurn(r);else E.playCard(r,i);}else if(r.phase==='victory')E.advance(r,r.rewards[0]);else E.resolveRoom(r,r.phase==='chest'?'claim':r.phase==='rest'?'rest':'leave');}assert.ok(['won','lost'].includes(r.phase));}});
test('ten choices lead to stage eleven boss; later enemies scale',()=>{const r=E.createRun('LONG');assert.deepEqual([...new Set(r.route.map(n=>n.row))],[0,1,2,3,4,5,6,7,8,9,10]);assert.equal(E.availableNodes(r).length,3);const boss=r.route.find(n=>n.type==='boss');assert.equal(boss.row,10);assert.equal(boss.enemy.hp,100);for(const n of r.route.filter(n=>n.row<10)){assert.ok(n.next.length>0);assert.ok(n.next.every(id=>r.route.find(x=>x.id===id).row===n.row+1));}const late=r.route.find(n=>n.row===8);assert.ok(late.enemy.hp>=53);assert.ok(late.enemy.moves.filter(m=>m.kind==='attack').every(m=>m.value>=8));});

test('neutral card pool contains all twelve new techniques and key effects resolve',()=>{for(const id of ['meteor','chainlightning','shatterarmour','lifesiphon','crystalbarrier','echocrystal','gravitywell','finishingblow','unstablecore','vengefulspirit','warcry','ancientrelic'])assert.ok(E.CARDS[id],id);const r=battle();r.battle.enemies.push(structuredClone(r.battle.enemies[0]));hand(r,['chainlightning']);r.battle.enemies.forEach(e=>{e.hp=e.maxHp=100});E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,94);assert.equal(r.battle.enemies[1].hp,97);hand(r,['shatterarmour']);r.battle.enemies[0].block=20;E.playCard(r,0);assert.equal(r.battle.enemies[0].block,0);assert.equal(r.battle.enemies[0].hp,90);hand(r,['echocrystal','strike']);E.playCard(r,0);E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,78);hand(r,['warcry']);E.playCard(r,0);assert.equal(r.battle.power,2);assert.ok(E.RELICS.hourglass&&E.RELICS.moonchalice&&E.RELICS.hunterlens);});
test('treasure outcomes are deterministic and approximately twenty percent cursed',()=>{let bad=0,total=0;for(let i=0;i<200;i++){const r=E.createRun('TREASURE'+i),chest=r.route.find(n=>n.type==='chest'),prev=r.route.find(n=>n.next.includes(chest.id));r.current=prev.id;r.visited=[prev.id];assert.ok(E.chooseNode(r,chest.id));bad+=r.room.bad?1:0;total++;const clone=E.createRun('TREASURE'+i);clone.current=prev.id;clone.visited=[prev.id];E.chooseNode(clone,chest.id);assert.equal(clone.room.bad,r.room.bad);}assert.ok(bad>=25&&bad<=55,`bad=${bad}/${total}`);});
test('relic effects alter battle economy and potions',()=>{const r=battle();r.relics.push('moonchalice');r.potions=1;r.hp=20;assert.ok(E.usePotion(r));assert.equal(r.hp,48);const g=E.createRun('GOLD');E.enterBattle(g);g.relics.push('gilded');g.battle.enemies.forEach(e=>e.hp=1);hand(g,['cleave']);const before=g.gold;E.playCard(g,0);assert.equal(g.gold,before+40);});

test('Core carries between turns, regenerates three and caps at ten',()=>{const r=battle();assert.equal(r.core,3);r.core=2;E.endTurn(r);assert.equal(r.core,5);r.core=9;E.endTurn(r);assert.equal(r.core,10);hand(r,['unstablecore']);r.core=10;E.playCard(r,0);assert.equal(r.core,10);E.endTurn(r);assert.equal(r.core,9);});
