import test from 'node:test';import assert from 'node:assert/strict';import * as E from '../engine.js';
const battle=()=>{const r=E.createRun('CHECK');E.enterBattle(r);return r;};
function hand(r,ids){r.battle.hand=ids;r.core=20;for(const e of r.battle.enemies){e.hp=100;e.maxHp=100;e.block=0;}}
test('seeded routes fork, reconnect and reject unreachable/repeated choices',()=>{const r=E.createRun('A');assert.deepEqual(r,E.createRun('A'));assert.notDeepEqual(r.route,E.createRun('B').route);assert.equal(E.chooseNode(r,'2-0'),false);E.chooseNode(r,'0-0');assert.equal(E.chooseNode(r,'0-0'),false);assert.equal(r.deck.length,10);assert.equal(new Set(r.deck).size,4);});
test('all ten printed card effects including Mark, stun and area damage',()=>{const r=battle();hand(r,['targetbreaker','gauntletsmash']);E.playCard(r,0);assert.equal(r.battle.enemies[0].mark,2);E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,82);hand(r,['stonebulwark','seismicpunch']);E.playCard(r,0);E.playCard(r,0);const hp=r.hp;E.endTurn(r);assert.equal(r.hp,hp);hand(r,['ironskin','strike','guard','deflect','focus','cleave']);r.block=0;E.playCard(r,0);assert.equal(r.block,8);assert.equal(r.battle.strength,1);E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,93);E.playCard(r,0);E.playCard(r,0);assert.equal(r.block,18);const core=r.core;E.playCard(r,0);assert.equal(r.core,core);r.battle.enemies.push(structuredClone(r.battle.enemies[0]));E.playCard(r,0);assert.equal(r.battle.enemies[0].hp,84);assert.equal(r.battle.enemies[1].hp,84);});
test('reward selected once; shop transactions conserve gold and prevent repeat buying',()=>{const r=battle();r.battle.enemies[0].hp=1;hand(r,['strike']);r.battle.enemies[0].hp=1;E.playCard(r,0);assert.equal(r.phase,'victory');const id=r.rewards[0];assert.equal(E.advance(r,id),true);assert.equal(r.deck.length,11);assert.equal(E.advance(r,id),false);r.phase='shop';r.room={stock:[{kind:'card',id:'deflect',price:25,sold:false}]};const gold=r.gold;assert.equal(E.buy(r,0),true);assert.equal(r.gold,gold-25);assert.equal(E.buy(r,0),false);assert.equal(E.sell(r,'card',0),true);assert.equal(r.gold,gold-15);});
test('save/reload preserves exact state and future random draws',()=>{const a=battle();E.endTurn(a);const b=E.restore(E.serialise(a));assert.ok(b);E.endTurn(a);E.endTurn(b);assert.deepEqual(a,b);assert.equal(E.restore('{}'),null);a.deck[0]='bad';assert.equal(E.restore(E.serialise(a)),null);});
test('chests and mysteries apply once, potion and risk effects work',()=>{const r=E.createRun('CHEST');r.phase='chest';r.room={relic:'amber',gold:25};assert.ok(E.resolveRoom(r,'claim'));assert.equal(r.potions,1);assert.equal(E.resolveRoom(r,'claim'),false);r.hp=40;assert.ok(E.usePotion(r));assert.equal(r.hp,60);r.phase='mystery';r.room={kind:'rift',cards:['cleave']};E.resolveRoom(r,'accept');assert.equal(r.curse,2);E.enterBattle(r);assert.equal(r.core,2);E.endTurn(r);assert.equal(r.core,2);E.endTurn(r);assert.equal(r.core,3);});
test('reachable runs across seeds finish with valid checkpoints',()=>{for(let seed=0;seed<15;seed++){const r=E.createRun('RUN'+seed);for(let step=0;step<500&&!['won','lost'].includes(r.phase);step++){assert.ok(E.restore(E.serialise(r)),r.phase);if(r.phase==='map')E.chooseNode(r,E.availableNodes(r)[0]);else if(r.phase==='combat'){let i=r.battle.hand.findIndex(id=>E.CARDS[id].cost<=r.core&&(E.CARDS[id].damage||E.CARDS[id].block));if(i<0)E.endTurn(r);else E.playCard(r,i);}else if(r.phase==='victory')E.advance(r,r.rewards[0]);else E.resolveRoom(r,r.phase==='chest'?'claim':r.phase==='rest'?'rest':'leave');}assert.ok(['won','lost'].includes(r.phase));}});
test('ten choices lead to stage eleven boss; later enemies scale',()=>{const r=E.createRun('LONG');assert.deepEqual([...new Set(r.route.map(n=>n.row))],[0,1,2,3,4,5,6,7,8,9,10]);assert.equal(E.availableNodes(r).length,3);const boss=r.route.find(n=>n.type==='boss');assert.equal(boss.row,10);assert.equal(boss.enemy.hp,100);for(const n of r.route.filter(n=>n.row<10)){assert.ok(n.next.length>0);assert.ok(n.next.every(id=>r.route.find(x=>x.id===id).row===n.row+1));}const late=r.route.find(n=>n.row===8);assert.ok(late.enemy.hp>=53);assert.ok(late.enemy.moves.filter(m=>m.kind==='attack').every(m=>m.value>=8));});
