
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,chooseNode,resolveRoom,restore,serialise,advance,endTurn,playCard,CARDS,CARD_UPGRADES,continueStage} from '../engine.js';
function fixture(eventId){
 const r=createRun('EVENT-CHECK');r.current=r.route[0].id;r.visited=[r.current];r.phase='mystery';
 r.room={eventVersion:1,eventId,kind:eventId,cards:['focus','cleave','warcry'],rare:['starfall','warcry','ancientrelic'],relic:'amber',success:true,trialEnemy:structuredClone(r.route.find(n=>n.type==='elite').enemy),step:'offer',result:null};
 return r;
}
test('forge charges gold once and upgrades one copy',()=>{const r=fixture('forge');assert.equal(resolveRoom(r,'forge:0:gold'),true);assert.equal(r.gold,10);assert.equal(r.deck[0],'strike_up');assert.equal(r.deck[1],'strike');assert.equal(resolveRoom(r,'forge:0:gold'),false);});
test('forge health payment leaves the hero alive',()=>{const r=fixture('forge');r.hp=10;assert.equal(resolveRoom(r,'forge:0:health'),false);r.hp=11;assert.equal(resolveRoom(r,'forge:0:health'),true);assert.equal(r.hp,1);assert.equal(r.gold,60);});
test('forge rejects insufficient gold and already upgraded cards',()=>{const r=fixture('forge');r.gold=49;assert.equal(resolveRoom(r,'forge:0:gold'),false);r.deck[0]='strike_up';assert.equal(resolveRoom(r,'forge:0:health'),false);assert.equal(r.hp,80);});
test('memory exchange preserves deck size and has no cost',()=>{const r=fixture('exchange'),size=r.deck.length;assert.equal(resolveRoom(r,'exchange:0:focus'),true);assert.equal(r.deck.length,size);assert.equal(r.deck[0],'focus');assert.equal(r.gold,60);});
test('memory exchange rejects a card outside the preview',()=>{const r=fixture('exchange');assert.equal(resolveRoom(r,'exchange:0:meteor'),false);assert.equal(r.deck[0],'strike');});
test('crystal safe reward cannot be claimed twice',()=>{const r=fixture('crystal');assert.equal(resolveRoom(r,'safe'),true);assert.equal(resolveRoom(r,'safe'),false);assert.equal(resolveRoom(r,'risk'),false);assert.equal(r.gold,100);});
test('crystal successful risk grants the shown stored relic',()=>{const r=fixture('crystal');resolveRoom(r,'risk');assert.deepEqual(r.relics,['amber']);assert.equal(r.hp,80);});
test('crystal failure cannot kill the hero',()=>{const r=fixture('crystal');r.room.success=false;r.hp=4;resolveRoom(r,'risk');assert.equal(r.hp,1);});
test('crystal completion and result survive reload without another reward',()=>{const r=fixture('crystal');resolveRoom(r,'risk');const saved=restore(serialise(r));assert.ok(saved);assert.equal(resolveRoom(saved,'risk'),false);assert.deepEqual(saved.relics,['amber']);});
test('crystal outcome survives reload before choosing',()=>{const r=fixture('crystal');r.room.success=false;const saved=restore(serialise(r));assert.ok(saved);resolveRoom(saved,'risk');assert.equal(saved.hp,68);assert.deepEqual(saved.relics,[]);});
test('explorer trades one potion for the chosen rare card',()=>{const r=fixture('explorer');r.potions=1;assert.equal(resolveRoom(r,'potion:starfall'),true);assert.equal(r.potions,0);assert.equal(r.deck.at(-1),'starfall');});
test('explorer rejects absent potions and invalid rare choices',()=>{const r=fixture('explorer');assert.equal(resolveRoom(r,'potion:starfall'),false);r.potions=1;assert.equal(resolveRoom(r,'potion:strike'),false);assert.equal(r.potions,1);});
test('explorer gold reward charges once',()=>{const r=fixture('explorer');resolveRoom(r,'gold');assert.equal(r.gold,35);assert.equal(r.deck.at(-1),'focus');assert.equal(resolveRoom(r,'gold'),false);assert.equal(r.gold,35);});
test('armoury costs health only after a valid selection',()=>{const r=fixture('armoury');assert.equal(resolveRoom(r,'armoury:strike'),false);assert.equal(r.hp,80);assert.equal(resolveRoom(r,'armoury:cleave'),true);assert.equal(r.hp,68);assert.equal(r.deck.at(-1),'cleave_up');});
test('armoury refuses fatal payments',()=>{const r=fixture('armoury');r.hp=12;assert.equal(resolveRoom(r,'armoury:cleave'),false);assert.equal(r.deck.length,10);});
test('beastkeeper supplies are mutually exclusive',()=>{for(const choice of ['basic','refined','gold']){const r=fixture('remains');assert.equal(resolveRoom(r,choice),true);assert.equal(resolveRoom(r,'gold'),false);assert.equal(r.shards.basic,choice==='basic'?8:5);assert.equal(r.shards.refined,choice==='refined'?1:0);assert.equal(r.gold,choice==='gold'?80:60);}});
test('whisper penalty is stored as battles, not turns',()=>{const r=fixture('whisper');resolveRoom(r,'accept');assert.equal(r.eventCorePenalty,2);assert.deepEqual(r.relics,['amber']);const saved=restore(serialise(r));assert.ok(saved);assert.equal(saved.eventCorePenalty,2);});
function startSimple(r){r.core=0;r.phase='map';r.debugUnlockAll=true;const node=r.route.find(n=>n.type==='battle');assert.equal(chooseNode(r,node.id),true);}
test('whisper drains only the first turn and consumes one battle',()=>{const r=createRun('CORE');r.eventCorePenalty=2;startSimple(r);assert.equal(r.core,2);assert.equal(r.eventCorePenalty,1);r.core=0;r.battle.enemies.forEach(e=>e.stunned=true);endTurn(r);assert.equal(r.core,3);assert.equal(r.eventCorePenalty,1);});
test('whisper expires after two battles',()=>{const r=createRun('CORE');r.eventCorePenalty=2;startSimple(r);assert.equal(r.core,2);startSimple(r);assert.equal(r.core,2);assert.equal(r.eventCorePenalty,0);startSimple(r);assert.equal(r.core,3);});
test('trial combat keeps the mystery route node intact',()=>{const r=fixture('trial'),id=r.current,kind=r.route[0].type;assert.equal(resolveRoom(r,'fight'),true);assert.equal(r.phase,'combat');assert.equal(r.battle.eventTrial,true);assert.equal(r.current,id);assert.equal(r.route[0].type,kind);assert.ok(restore(serialise(r)));});
test('trial victory grants extra gold and offers upgrade after card reward',()=>{const r=fixture('trial');resolveRoom(r,'fight');r.battle.enemies.forEach(e=>{e.hp=1;e.block=0;});r.battle.hand=[...r.deck];r.battle.draw=[];playCard(r,0);assert.equal(r.phase,'victory');assert.equal(r.lastCombatGold,85);assert.equal(r.gold,145);assert.equal(r.trialUpgradePending,true);assert.ok(restore(serialise(r)));assert.equal(advance(r),true);assert.equal(r.phase,'mystery');assert.equal(r.room.step,'upgrade');assert.ok(restore(serialise(r)));assert.equal(resolveRoom(r,'upgrade:1'),true);assert.equal(r.deck[1],'strike_up');assert.equal(r.phase,'map');});
test('trial upgrade refuses invalid selection',()=>{const r=fixture('trial');r.room.step='upgrade';assert.equal(resolveRoom(r,'upgrade:99'),false);assert.equal(r.deck[0],'strike');});
test('every event can be declined without a cost',()=>{for(const id of ['forge','exchange','crystal','explorer','armoury','remains','whisper','trial']){const r=fixture(id);assert.equal(resolveRoom(r,'leave'),true);assert.equal(r.hp,80);assert.equal(r.gold,60);assert.equal(r.deck.length,10);assert.deepEqual(r.relics,[]);}});
test('legacy mystery offers retain their original rules',()=>{const r=fixture('exchange');r.room={kind:'cache',cards:['focus']};assert.equal(resolveRoom(r,'focus'),true);assert.equal(r.deck.at(-1),'focus');});
test('old saves receive default event penalty',()=>{const r=createRun('OLD');delete r.eventCorePenalty;const saved=restore(serialise(r));assert.ok(saved);assert.equal(saved.eventCorePenalty,0);});
test('event identities do not repeat within a stage and rewards are seeded',()=>{for(let seed=0;seed<20;seed++){const r=createRun('POOL-'+seed);r.debugUnlockAll=true;const ids=[];for(const n of r.route.filter(n=>n.type==='mystery')){r.phase='map';chooseNode(r,n.id);ids.push(r.room.eventId);const twin=createRun('POOL-'+seed);twin.debugUnlockAll=true;chooseNode(twin,n.id);assert.deepEqual(r.room,twin.room);assert.ok(r.room.cards.every(id=>!CARDS[id].ilyra));}assert.equal(new Set(ids).size,ids.length);}});
test('Ilyra event cards cannot award Kaerun techniques',()=>{for(let seed=0;seed<20;seed++){const r=createRun('ILYRA-'+seed,'ilyra');r.debugUnlockAll=true;for(const n of r.route.filter(n=>n.type==='mystery')){r.phase='map';chooseNode(r,n.id);assert.ok([...r.room.cards,...r.room.rare].every(id=>!CARDS[id].kaerun));}}});

test('Stage 2 events use the same unique seeded pool',()=>{for(let seed=0;seed<10;seed++){const r=createRun('CAVERN-'+seed);r.phase='stage-complete';continueStage(r);r.debugUnlockAll=true;const ids=[];for(const n of r.route.filter(n=>n.type==='mystery')){r.phase='map';chooseNode(r,n.id);ids.push(r.room.eventId);}assert.equal(new Set(ids).size,ids.length);}});
test('active battle reload does not consume a second whisper penalty',()=>{const r=createRun('RELOAD-CORE');r.eventCorePenalty=2;startSimple(r);const saved=restore(serialise(r));assert.ok(saved);assert.equal(saved.core,2);assert.equal(saved.eventCorePenalty,1);});
