import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_STARTERS,FLEX_SLOTS,LEVEL_UNLOCKS,STARTER_CHALLENGES,emptyStarterStats,restoreStarterCollection,defaultLoadout,unlockedStarterCards,validateLoadout,buildStarterDeck,chooseLevelUnlock,bankStarterProgress} from '../starter-decks.js';
import {CARDS,createRun,enterBattle,playCard,endTurn,restore,serialise} from '../engine.js';

test('four flexible slots preserve original decks and six fixed cards',()=>{for(const hero of ['kaerun','ilyra']){const c=restoreStarterCollection(null),d=buildStarterDeck(hero,defaultLoadout(hero),c,1,CARDS);assert.deepEqual(d,DEFAULT_STARTERS[hero]);assert.equal(FLEX_SLOTS[hero].length,4);assert.equal(d.length,10);}});
test('hero levels offer one permanent choice per milestone',()=>{const c=restoreStarterCollection(null);assert.equal(chooseLevelUnlock(c,'kaerun',2,'scout',1),false);assert.equal(chooseLevelUnlock(c,'kaerun',2,'scout',2),true);assert.equal(chooseLevelUnlock(c,'kaerun',2,'deflect',2),false);assert.ok(unlockedStarterCards('kaerun',c,2).includes('scout'));assert.ok(!unlockedStarterCards('ilyra',c,2).includes('scout'));});
test('all unlock candidates are valid unupgraded cards for their hero',()=>{for(const hero of ['kaerun','ilyra'])for(const id of [...Object.values(LEVEL_UNLOCKS[hero]).flat(),...STARTER_CHALLENGES[hero].map(x=>x.card)]){assert.ok(CARDS[id]);assert.ok(!CARDS[id].upgradeOf);assert.ok(CARDS[id].cost<=2);assert.ok(!CARDS[id][hero==='kaerun'?'ilyra':'kaerun']);}});
test('locked, upgraded and foreign hero cards cannot be slotted',()=>{const c=restoreStarterCollection(null);for(const id of ['scout','strike_up','arcbolt','sovereignimpact','unknown'])assert.ok(validateLoadout('kaerun',['strike','strike','guard',id],c,20,CARDS));});
test('duplicate and cost budgets apply to the four flexible cards',()=>{const c=restoreStarterCollection(null);assert.ok(validateLoadout('kaerun',['strike','strike','strike','guard'],c,1,CARDS));assert.ok(validateLoadout('kaerun',['gauntletsmash','gauntletsmash','targetbreaker','guard'],c,1,CARDS)===null);assert.ok(validateLoadout('kaerun',['gauntletsmash','gauntletsmash','targetbreaker','gauntletsmash'],c,1,CARDS));});
test('saved loadout replaces only flexible indexes and feeds new runs',()=>{const c=restoreStarterCollection(null);chooseLevelUnlock(c,'kaerun',2,'scout',2);const loadout=['scout','strike','guard','guard'],r=createRun('CUSTOM','kaerun',{characterLevel:2,starterCollection:c,starterLoadout:loadout});assert.equal(r.deck[2],'scout');r.deck.forEach((id,i)=>{if(!FLEX_SLOTS.kaerun.includes(i))assert.equal(id,DEFAULT_STARTERS.kaerun[i]);});enterBattle(r);assert.deepEqual([...r.battle.draw,...r.battle.hand].sort(),[...r.deck].sort());assert.ok(restore(serialise(r)));});
test('invalid persisted loadout falls back to original without losing run compatibility',()=>{const c=restoreStarterCollection(null);const r=createRun('INVALID','ilyra',{starterCollection:c,starterLoadout:['strike','strike','strike','strike']});assert.deepEqual(r.deck,DEFAULT_STARTERS.ilyra);assert.ok(restore(serialise(r)));});
test('all six challenges unlock on the exact threshold and stay hero-specific',()=>{for(const hero of ['kaerun','ilyra'])for(const ch of STARTER_CHALLENGES[hero]){const c=restoreStarterCollection(null);c.heroes[hero].stats[ch.stat]=ch.goal-1;assert.ok(!unlockedStarterCards(hero,c,1).includes(ch.card));c.heroes[hero].stats[ch.stat]++;assert.ok(unlockedStarterCards(hero,c,1).includes(ch.card));}});
test('progress checkpoint survives reload and repeated saves without double credit',()=>{let c=restoreStarterCollection(null);const r={starterRunId:'one',hero:'kaerun',starterStats:{...emptyStarterStats(),markedKills:12},deck:['strike'],rewards:['focus']};assert.equal(bankStarterProgress(c,r),true);assert.equal(bankStarterProgress(c,r),false);c=restoreStarterCollection(JSON.stringify(c));assert.equal(bankStarterProgress(c,r),false);assert.equal(c.heroes.kaerun.stats.markedKills,12);r.starterStats.markedKills=15;bankStarterProgress(c,r);assert.equal(c.heroes.kaerun.stats.markedKills,15);assert.ok(c.heroes.kaerun.seen.includes('focus'));});
test('new ascents add progress, including failed runs',()=>{const c=restoreStarterCollection(null);for(const id of ['run1','run2'])bankStarterProgress(c,{starterRunId:id,hero:'ilyra',phase:'lost',starterStats:{...emptyStarterStats(),resonanceSpent:25},deck:[]});assert.equal(c.heroes.ilyra.stats.resonanceSpent,50);assert.ok(unlockedStarterCards('ilyra',c,1).includes('corechannel'));});
test('collection sanitises corrupt stats and unlock choices',()=>{const c=restoreStarterCollection({heroes:{kaerun:{stats:{markedKills:-10,marksApplied:Infinity},choices:{2:'sovereignimpact'},loadout:['strike_up','x','x','x']}}});assert.equal(c.heroes.kaerun.stats.markedKills,0);assert.deepEqual(c.heroes.kaerun.choices,{});assert.deepEqual(c.heroes.kaerun.loadout,defaultLoadout('kaerun'));});
function battle(hero,card){const r=createRun('CHALLENGE',hero);r.deck[0]=card;enterBattle(r);r.battle.hand=[...r.deck];r.battle.draw=[];r.core=10;return r;}
test('Mark applications count successful cards once',()=>{const r=battle('kaerun','targetbreaker');playCard(r,0);assert.equal(r.starterStats.marksApplied,1);r.core=0;assert.equal(playCard(r,0),false);assert.equal(r.starterStats.marksApplied,1);assert.ok(restore(serialise(r)));});
test('Marked kills count all affected foes before consume-Mark removes it',()=>{const r=battle('kaerun','sovereignimpact');r.battle.enemies[0].hp=1;r.battle.enemies[0].mark=3;playCard(r,0);assert.equal(r.starterStats.markedKills,1);});
test('blocked damage uses actual absorbed damage',()=>{const r=battle('kaerun','guard');const e=r.battle.enemies[0];r.battle.enemies=[e];e.moves=[{kind:'attack',value:9,hits:2}];e.move=0;r.block=12;endTurn(r);assert.equal(r.starterStats.blockedDamage,12);});
test('Ilyra tracks Resonance spending and Barrier',()=>{const r=battle('ilyra','prismward');r.battle.resonance=3;playCard(r,0);assert.equal(r.starterStats.resonanceSpent,3);assert.equal(r.starterStats.barrierCreated,6);assert.ok(restore(serialise(r)));});
test('Resonance-spending kills count actual defeated foes',()=>{const r=battle('ilyra','fracturefield');r.battle.resonance=3;r.battle.enemies.forEach(e=>e.hp=1);const count=r.battle.enemies.length;playCard(r,0);assert.equal(r.starterStats.resonanceKills,count);});
test('older run saves receive empty challenge counters',()=>{const r=createRun('OLD');delete r.starterStats;const loaded=restore(serialise(r));assert.ok(loaded);assert.deepEqual(loaded.starterStats,emptyStarterStats());});
test('hero loadouts remain independent after collection reload',()=>{let c=restoreStarterCollection(null);chooseLevelUnlock(c,'kaerun',2,'scout',2);c.heroes.kaerun.loadout=['scout','strike','guard','guard'];c=restoreStarterCollection(JSON.stringify(c));assert.equal(c.heroes.kaerun.loadout[0],'scout');assert.deepEqual(c.heroes.ilyra.loadout,defaultLoadout('ilyra'));});
