import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../engine.js';
import {accountProgress,heroUnlocked,vaelisBonuses} from '../progression.js';
import {restoreStarterCollection,defaultLoadout,FLEX_SLOTS,STARTER_CHALLENGES,bankStarterProgress,unlockedStarterCards} from '../starter-decks.js';
function fight(cards=['venomcut'],level=1){const r=E.createRun('VENOM-TEST','vaelis',{characterLevel:level});E.enterBattle(r);r.deck=[...cards,...Array(5).fill('serpentguard')];Object.assign(r.battle,{hand:[...r.deck],draw:[],discard:[],exhaust:[],retained:[]});r.core=10;r.battle.enemies=[{...r.battle.enemies[0],hp:200,maxHp:200,block:0,move:0,poison:0,moves:[{kind:'attack',value:5}]}];return r;}
function play(r,id){assert.equal(E.playCard(r,r.battle.hand.indexOf(id)),true);}
test('Account Rank 5 unlocks at 690 shared XP and includes existing hero progress',()=>{assert.equal(accountProgress({kaerunXp:300,ilyraXp:389}).rank,4);assert.equal(heroUnlocked('vaelis',{kaerunXp:300,ilyraXp:390}),true);assert.equal(heroUnlocked('vaelis',{vaelisXp:689}),false);assert.equal(heroUnlocked('dhoran',{kaerunXp:99999}),false);assert.equal(accountProgress({kaerunXp:NaN,ilyraXp:-4}).rank,1);});
test('Vaelis has 12 exclusive cards, each with an upgrade, and four flexible slots',()=>{const ids=Object.keys(E.CARDS).filter(id=>E.CARDS[id].vaelis&&!E.CARDS[id].upgradeOf);assert.equal(ids.length,12);for(const id of ids)assert.equal(E.CARDS[E.CARD_UPGRADES[id]].upgradeOf,id);assert.equal(FLEX_SLOTS.vaelis.length,4);const c=restoreStarterCollection(null),r=E.createRun('DECK','vaelis',{starterCollection:c,starterLoadout:defaultLoadout('vaelis')});assert.equal(r.deck.length,10);assert.ok(r.deck.every(id=>E.CARDS[id].vaelis));});
test('Venomcraft adds stacks only to the first application per turn',()=>{const r=fight(['venomcut','toxicprimer']);play(r,'venomcut');assert.equal(r.battle.enemies[0].poison,3);play(r,'toxicprimer');assert.equal(r.battle.enemies[0].poison,7);assert.equal(r.starterStats.poisonApplied,7);E.endTurn(r);assert.equal(r.battle.venomUsed,false);});
test('Poison ignores Block, ticks before enemy action and decays by one',()=>{const r=fight(),e=r.battle.enemies[0];e.poison=7;e.block=100;r.block=20;E.endTurn(r);assert.equal(e.hp,193);assert.equal(e.poison,6);assert.equal(r.hp,80);assert.equal(r.starterStats.poisonDamage,7);});
test('lethal Poison prevents the enemy action and grants normal victory XP',()=>{const r=fight(),e=r.battle.enemies[0];e.hp=3;e.poison=7;E.endTurn(r);assert.equal(r.hp,80);assert.equal(r.phase,'victory');assert.equal(r.characterXpEarned,12);assert.equal(r.starterStats.poisonDamage,3);assert.equal(r.starterStats.poisonKills,1);});
test('Poison ticks on stunned enemies and does not count direct kills',()=>{const r=fight(['venomcut']),e=r.battle.enemies[0];e.poison=2;e.stunned=true;E.endTurn(r);assert.equal(e.hp,198);assert.equal(e.poison,1);assert.equal(r.hp,80);r.battle.hand=['venomcut'];e.hp=1;r.core=10;play(r,'venomcut');assert.equal(r.starterStats.poisonKills,0);assert.equal(r.starterStats.poisonApplied,0);});
test('Venom Rupture consumes Poison once, including Echo repetition',()=>{const r=fight(['venomrupture']);r.battle.enemies[0].poison=5;r.battle.echo=true;play(r,'venomrupture');assert.equal(r.battle.enemies[0].hp,169);assert.equal(r.battle.enemies[0].poison,0);assert.equal(r.starterStats.poisonDamage,0);});
test('Death Bloom uses each target’s own Poison and consumes it',()=>{const r=fight(['deathbloom']);r.battle.enemies.push(structuredClone(r.battle.enemies[0]));r.battle.enemies[0].poison=3;r.battle.enemies[1].poison=5;play(r,'deathbloom');assert.deepEqual(r.battle.enemies.map(e=>e.hp),[187,183]);assert.deepEqual(r.battle.enemies.map(e=>e.poison),[0,0]);assert.ok(r.battle.exhaust.includes('deathbloom'));});
test('Toxic Mist applies to living enemies with one passive bonus total',()=>{const r=fight(['toxicmist']);r.battle.enemies.push(structuredClone(r.battle.enemies[0]),{...r.battle.enemies[0],hp:0});play(r,'toxicmist');assert.deepEqual(r.battle.enemies.map(e=>e.poison),[3,2,0]);});
test('Catalyst cannot invent Poison on a clean target, and caps stacks',()=>{const r=fight(['catalyst']);play(r,'catalyst');assert.equal(r.battle.enemies[0].poison,0);assert.equal(r.battle.venomUsed,false);const q=fight(['catalyst_up']);q.battle.enemies[0].poison=500;play(q,'catalyst_up');assert.equal(q.battle.enemies[0].poison,999);assert.equal(q.starterStats.poisonApplied,499);});
test('Mist Step evades exactly one hit of a multi-hit attack and exhausts',()=>{const r=fight(['miststep']),e=r.battle.enemies[0];e.moves=[{kind:'attack',value:10,hits:2}];play(r,'miststep');E.endTurn(r);assert.equal(r.hp,74);assert.equal(r.battle.evade,0);assert.ok(r.battle.exhaust.includes('miststep'));});
test('unused evasion expires when enemies do not attack',()=>{const r=fight(['miststep']);r.battle.enemies[0].moves=[{kind:'guard',value:0}];play(r,'miststep');E.endTurn(r);assert.equal(r.battle.evade,0);});
test('all 20 mastery levels survive save reload with matching Vitality and active poison',()=>{for(let level=1;level<=20;level++){const r=fight(['toxicprimer'],level);play(r,'toxicprimer');const restored=E.restore(E.serialise(r));assert.ok(restored,'level '+level);assert.equal(restored.maxHp,80+vaelisBonuses(level).maxHp);assert.equal(restored.battle.enemies[0].poison,4+vaelisBonuses(level).poisonBonus);}});
test('old saves gain additive counters and new poison fields without losing their run',()=>{const r=E.createRun('OLD','kaerun');E.enterBattle(r);for(const k of ['poisonApplied','poisonDamage','poisonKills'])delete r.starterStats[k];delete r.battle.evade;delete r.battle.venomUsed;delete r.battle.venomDrawUsed;for(const e of r.battle.enemies)delete e.poison;assert.ok(E.restore(E.serialise(r)));});
test('corrupt poison and evasion saves are rejected',()=>{const r=fight();r.battle.enemies[0].poison=-1;assert.equal(E.restore(E.serialise(r)),null);r.battle.enemies[0].poison=0;r.battle.evade=2;assert.equal(E.restore(E.serialise(r)),null);});
test('poison challenges persist across defeats without duplicate credit',()=>{const c=restoreStarterCollection(null),r=fight();r.starterRunId='VAELIS-CHALLENGES';r.phase='lost';for(const task of STARTER_CHALLENGES.vaelis)r.starterStats[task.stat]=task.goal;assert.equal(bankStarterProgress(c,r),true);assert.equal(bankStarterProgress(c,r),false);for(const task of STARTER_CHALLENGES.vaelis)assert.ok(unlockedStarterCards('vaelis',c).includes(task.card));});
test('reward pools keep all three heroes’ exclusive cards separate',()=>{for(const hero of ['kaerun','ilyra','vaelis'])for(let i=0;i<30;i++){const r=E.createRun('POOL'+i,hero);E.enterBattle(r);for(const e of r.battle.enemies){e.hp=1;e.block=0;}r.battle.hand=['cleave'];r.core=10;E.playCard(r,0);assert.equal(r.phase,'victory');for(const id of r.rewards)for(const other of ['kaerun','ilyra','vaelis'].filter(h=>h!==hero))assert.ok(!E.CARDS[id][other],hero+' received '+id);}});
